package com.wallshift.app.ui.theme

import androidx.compose.ui.graphics.Color

// Light theme colors
val LightPrimary = Color(0xFF1A3A5C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD3E4FF)
val LightOnPrimaryContainer = Color(0xFF001C3A)
val LightSecondary = Color(0xFF545F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD8E3F8)
val LightOnSecondaryContainer = Color(0xFF111C2B)
val LightTertiary = Color(0xFF6D5676)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF6D9FF)
val LightOnTertiaryContainer = Color(0xFF261430)
val LightBackground = Color(0xFFF8F9FF)
val LightOnBackground = Color(0xFF191C20)
val LightSurface = Color(0xFFF8F9FF)
val LightOnSurface = Color(0xFF191C20)
val LightSurfaceVariant = Color(0xFFDFE2EB)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)

// Dark theme colors
val DarkPrimary = Color(0xFFA3C9FF)
val DarkOnPrimary = Color(0xFF00315E)
val DarkPrimaryContainer = Color(0xFF004884)
val DarkOnPrimaryContainer = Color(0xFFD3E4FF)
val DarkSecondary = Color(0xFFBCC7DB)
val DarkOnSecondary = Color(0xFF263141)
val DarkSecondaryContainer = Color(0xFF3D4758)
val DarkOnSecondaryContainer = Color(0xFFD8E3F8)
val DarkTertiary = Color(0xFFD9BDE3)
val DarkOnTertiary = Color(0xFF3D2946)
val DarkTertiaryContainer = Color(0xFF543F5D)
val DarkOnTertiaryContainer = Color(0xFFF6D9FF)
val DarkBackground = Color(0xFF111318)
val DarkOnBackground = Color(0xFFE1E2E9)
val DarkSurface = Color(0xFF111318)
val DarkOnSurface = Color(0xFFE1E2E9)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
